'use strict';
/*
 *  File: presentations.js
 *  Type: Schema
 *  Generated by: Mongoose-Fixture (v0.3.1)
 *
 *
 */

module.exports = function (mongoose) {

    var exportSchema = mongoose.Schema({
                upDatedOn: Date,
                presentationData: [
                    {
                        keyVals: {},
                        templateName: String,
                        apps: [
                            {name: String, params: {}}
                        ]
                    }
                ],
                script: [
                    {
                        fnName: String,
                        actionInitiated: Number,
                        args: {},
                        module: String
                    }
                ],
                recordingStarted: Date,
                annotation: {},
                files: [],
                audioLocation: String,
                audioId: String,
                authors: [
                    {
                        username: String,
                        description: String,
                        role: String,
                        percentageContribution: Number
                    }
                ],
                voting: {
                    upVote: Number,
                    downVote: Number
                },

                contentParams: {
                    concept: [String],
                    subject: [String],
                    location: String,
                    language: [String],
                    boardMap: {board: String, standard: Number}
                },
                deleted: Boolean,
                summary: String
            }
        )
        ;


// By Default we export the schema
// You could alter this returning void
// and registering your model with the db connection
// conn.model('ModelName', exportSchema);
    return exportSchema;
}
;
