/*
 *  File: users.js
 *  Type: Schema
 *  Generated by: Mongoose-Fixture (v0.2.3)
 *
 *
 */

module.exports = function (mongoose) {
    'use strict';

    /**
     * User Schema
     */
    return new mongoose.Schema({
        name: String,
        email: String,
        username: {
            type: String,
            unique: true
        },
        hashed_password: String,
        provider: String,
        salt: String,
        facebook: {},
        twitter: {},
        github: {},
        google: {}
    });

};
